name: Executar Python

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo
      uses: actions/checkout@v5

    - name: Instalar Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Mostrar versão Python
      run: python --version

    - name: Rodar script
      run: python DB/CriarBancoDeDados.py
